-- Private media buckets. The application issues short-lived signed URLs after it
-- has checked the visibility of the associated profile, wish or fundraiser.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('avatars', 'avatars', false, 5242880, array['image/jpeg', 'image/png', 'image/webp']),
  ('wish-media', 'wish-media', false, 10485760, array['image/jpeg', 'image/png', 'image/webp']),
  ('fundraiser-media', 'fundraiser-media', false, 10485760, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Object paths must begin with the authenticated user's UUID:
--   {user-id}/{uuid}.{extension}
-- This makes ownership checks independent of the browser-provided filename.
create policy "users upload own GiftOS media" on storage.objects for insert to authenticated with check (
  bucket_id in ('avatars', 'wish-media', 'fundraiser-media')
  and owner_id = auth.uid()
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "users update own GiftOS media" on storage.objects for update to authenticated using (
  bucket_id in ('avatars', 'wish-media', 'fundraiser-media') and owner_id = auth.uid()
) with check (
  bucket_id in ('avatars', 'wish-media', 'fundraiser-media')
  and owner_id = auth.uid()
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "users delete own GiftOS media" on storage.objects for delete to authenticated using (
  bucket_id in ('avatars', 'wish-media', 'fundraiser-media') and owner_id = auth.uid()
);

-- Reads go through signed URLs generated by server code after business-level
-- access checks. No broad storage.objects select policy is intentionally added.
